#pragma once

enum BlockType {
	WATER_DEEP = 0,
	WATER = 1,
	WATER_SHALLOW = 2,
	AMBER = 3,
	DESERT_PURPLE = 60,
	DESERT = 70,
	GRASS_LIGHT = 4,
	GRASS_PURPLE = 20,
	GRASS = 10,
	GRASS_OTHER = 5,
	MOUNTAIN_LOW = 40,
	MOUNTAIN_HIGH = 50
};