#pragma once

/**
* ѕредставл€ет собой виды клеток на карте.
*/
enum BlockType {
	WATER_DEEP = 0,
	WATER = 10,
	WATER_SHALLOW = 20,
	DESERT = 30,
	GRASS_PURPLE = 40,
	DESERT_PURPLE = 50,
	GRASS = 60,
	GRASS_TROPICAL = 70,

	MOUNTAIN_LOW = 80,
	MOUNTAIN_HIGH = 90,

	AMBER = 3,
	GRASS_LIGHT = 4,
	GRASS_OTHER = 5,
	ROCK = MOUNTAIN_LOW,
	UNKNOWN = 9,

	// For diagram
	GRASSLAND = GRASS,
	SCORCHED = MOUNTAIN_LOW,
	BARE = MOUNTAIN_HIGH,
	TEMPERATE_DESERT = DESERT,
	TROPICAL_SEASONAL_FOREST = GRASS_TROPICAL,

	// Placeholders
	SUBTROPICAL_DESERT = AMBER,
	SHRUBLAND = GRASS_OTHER,
	TEMPERATE_DECIDUOUS_FOREST = GRASS_OTHER,
	TROPICAL_RAIN_FOREST = 120,
	TEMPERATE_RAIN_FOREST = GRASSLAND,
	TAIGA = 93,
	TUNDRA = ROCK,
	SNOW = 8,
	CAVE_WALL = MOUNTAIN_LOW,
	CAVE_FLOOR = MOUNTAIN_HIGH
};